/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventorysystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 
 */
public class AddSupplierProduct extends javax.swing.JFrame {
    /**
     * Creates new form AddIncomingOrder
     */
    public AddSupplierProduct() {
        initComponents();
        getSuppliersData(listOfSuppliers);
    }
    
    public static void getSuppliersData(JComboBox<String> listOfSuppliers) {
//        JComboBox<String> listOfSuppliers = new JComboBox<>();
        listOfSuppliers.removeAllItems();

        String dbName = "InventorySystem";
        String dbUsername = "root";
        String dbPassword = "root";

        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/" + dbName, dbUsername, dbPassword)) {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from suppliers");
            while (rs.next()) {
                String data = rs.getString("supplierNickname");
                listOfSuppliers.addItem(data);
            }
            
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "An error occurred: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addOrderLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        addSupplierProductsTable = new javax.swing.JTable();
        listOfSuppliers = new javax.swing.JComboBox<>();
        price = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        addButton1 = new javax.swing.JButton();
        productName = new javax.swing.JTextField();
        description = new javax.swing.JTextField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addOrderLabel.setFont(new java.awt.Font("Nirmala UI", 1, 28)); // NOI18N
        addOrderLabel.setForeground(new java.awt.Color(255, 255, 255));
        addOrderLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/64/add.png"))); // NOI18N
        addOrderLabel.setText("ADD SUPPLIER PRODUCT");
        jPanel1.add(addOrderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 26, -1, -1));

        backButton.setBackground(new java.awt.Color(75, 130, 245));
        backButton.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/24/left-arrow.png"))); // NOI18N
        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 509, 120, -1));

        addSupplierProductsTable.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        addSupplierProductsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SUPPLIER", "PRODUCT", "DESCRIPTION", "PRICE", "DATE CREATED"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(addSupplierProductsTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 113, 830, -1));

        listOfSuppliers.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jPanel1.add(listOfSuppliers, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 113, 120, -1));

        price.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        price.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        price.setText("PRICE");
        price.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                priceFocusGained(evt);
            }
        });
        jPanel1.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 120, -1));

        saveButton.setBackground(new java.awt.Color(75, 130, 245));
        saveButton.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/24/diskette.png"))); // NOI18N
        saveButton.setText("SAVE");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jPanel1.add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 570, 120, -1));

        addButton.setBackground(new java.awt.Color(75, 130, 245));
        addButton.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/24/add (1).png"))); // NOI18N
        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 120, -1));

        addButton1.setBackground(new java.awt.Color(75, 130, 245));
        addButton1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        addButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/24/delete.png"))); // NOI18N
        addButton1.setText("DELETE");
        addButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(addButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 570, 120, -1));
        jPanel1.add(productName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 120, -1));
        jPanel1.add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 120, 100));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/warehouse1.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, -20, 1210, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        Suppliers S = new Suppliers();
        S.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String date = dateFormat.format(new Date());
        
        String supplier = (String) listOfSuppliers.getSelectedItem();
        String product = productName.getText();
        String des = description.getText();
        double priceInput = Double.parseDouble(price.getText());
        
        String dbName = "InventorySystem";
        String dbUsername = "root";
        String dbPassword = "root";
        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/" + dbName, dbUsername, dbPassword)) {
            String query = "SELECT * FROM supplierproducts WHERE supplierProductName = ?";
            PreparedStatement ps = con.prepareStatement(query);

            ps.setString(1, product);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Product of supplier already exist.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else {
                DefaultTableModel tablemodel = (DefaultTableModel)addSupplierProductsTable.getModel();
                String[] incomingOrdersData = {
                        supplier,
                        product,
                        des,
                        String.valueOf(priceInput),
                        date.split(" ")[0]
                    };

                    tablemodel.addRow(incomingOrdersData);
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "An error occurred: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void addButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButton1ActionPerformed
        DefaultTableModel tablemodel = (DefaultTableModel)addSupplierProductsTable.getModel();
        int[] sel = addSupplierProductsTable.getSelectedRows();
        
        if (sel.length == 0) {
            JOptionPane.showMessageDialog(null, "Please select a row to delete.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        for (int i = sel.length - 1; i >= 0; i--) {
            tablemodel.removeRow(sel[i]);
        }
    }//GEN-LAST:event_addButton1ActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        DefaultTableModel tablemodel = (DefaultTableModel)addSupplierProductsTable.getModel();
        addSupplierProductsTable.setRowSelectionInterval(0, addSupplierProductsTable.getRowCount() - 1);
        int[] selAll = addSupplierProductsTable.getSelectedRows();
        
        UserService userService = UserService.getInstance();
        String username = userService.getUsername();
        String date = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date());
        
        if (selAll.length == 0) {
            JOptionPane.showMessageDialog(null, "Please select a row to delete.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else {
            String dbName = "InventorySystem";
            String dbUsername = "root";
            String dbPassword = "root";

            try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/" + dbName, dbUsername, dbPassword)) {
                String query = "INSERT INTO supplierproducts (supplierProductName, supplierProductDescription, supplierProductPrice, supplierNickname, username, supplierProductCreated_at) VALUES (?, ?, ?, ?, ?, ?)";
                PreparedStatement ps = con.prepareStatement(query);

                for (int i = 0; i < selAll.length; i++) {
                    int rowIndex = selAll[i];

                    String supplier = (String) tablemodel.getValueAt(rowIndex, 0);
                    String product = (String) tablemodel.getValueAt(rowIndex, 1);  
                    String des = (String) tablemodel.getValueAt(rowIndex, 2);  
                    double priceInput = Double.parseDouble((String) tablemodel.getValueAt(rowIndex, 3));

                    ps.setString(1, product);
                    ps.setString(2, des);
                    ps.setDouble(3, priceInput); 
                    ps.setString(4, supplier);
                    ps.setString(5, username); 
                    ps.setString(6, date);

                    ps.execute();
                }

                JOptionPane.showMessageDialog(null, "Data saved successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                SupplierProducts SP = new SupplierProducts();
                SP.setVisible(true);
                this.dispose();

            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "An error occurred: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void priceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_priceFocusGained
        price.setText("");
    }//GEN-LAST:event_priceFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSupplierProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSupplierProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSupplierProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSupplierProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddSupplierProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton addButton1;
    private javax.swing.JLabel addOrderLabel;
    private javax.swing.JTable addSupplierProductsTable;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel background;
    private javax.swing.JTextField description;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> listOfSuppliers;
    private javax.swing.JTextField price;
    private javax.swing.JTextField productName;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
