/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventorysystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 
 */
public class AddUser extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public AddUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        passwordLabel1 = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();
        passwordInput = new javax.swing.JTextField();
        usernameInput = new javax.swing.JTextField();
        firstnameInput = new javax.swing.JTextField();
        firstnameLabel = new javax.swing.JLabel();
        lastnameInput = new javax.swing.JTextField();
        role = new javax.swing.JComboBox<>();
        gmailInput = new javax.swing.JTextField();
        gmailLabel = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passwordLabel1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        passwordLabel1.setText("USERROLE:");
        jPanel1.add(passwordLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        usernameLabel.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        usernameLabel.setText("USERNAME:");
        jPanel1.add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        passwordLabel.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        passwordLabel.setText("PASSWORD:");
        jPanel1.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        backButton.setBackground(new java.awt.Color(75, 130, 245));
        backButton.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/24/left-arrow.png"))); // NOI18N
        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 100, -1));

        registerButton.setBackground(new java.awt.Color(75, 130, 245));
        registerButton.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        registerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/24/contract.png"))); // NOI18N
        registerButton.setText("ADD");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        jPanel1.add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 100, -1));

        passwordInput.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        passwordInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(passwordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 198, -1));

        usernameInput.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        usernameInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(usernameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 198, -1));

        firstnameInput.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        firstnameInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        firstnameInput.setText("FIRSTNAME");
        firstnameInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstnameInputFocusGained(evt);
            }
        });
        jPanel1.add(firstnameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 90, -1));

        firstnameLabel.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        firstnameLabel.setText("NAME:");
        jPanel1.add(firstnameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        lastnameInput.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        lastnameInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lastnameInput.setText("LASTNAME");
        lastnameInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastnameInputFocusGained(evt);
            }
        });
        jPanel1.add(lastnameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 90, -1));

        role.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "WarehouseStaff", "Admin" }));
        jPanel1.add(role, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 200, -1));

        gmailInput.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        gmailInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(gmailInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 198, -1));

        gmailLabel.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        gmailLabel.setText("GMAIL:");
        jPanel1.add(gmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/monitor2.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -270, 610, 870));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void firstnameInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnameInputFocusGained
        firstnameInput.setText("");
    }//GEN-LAST:event_firstnameInputFocusGained

    private void lastnameInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnameInputFocusGained
        lastnameInput.setText("");
    }//GEN-LAST:event_lastnameInputFocusGained

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        try {
            String fname = firstnameInput.getText();
            String lname = lastnameInput.getText();
            String uname = usernameInput.getText();
            String gmail = gmailInput.getText();
            String pass = passwordInput.getText();
            String userRole = (String) role.getSelectedItem();

            if (fname.isEmpty() || lname.isEmpty() || uname.isEmpty() || gmail.isEmpty() || pass.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please fill out all required fields.", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                UserService userService = UserService.getInstance();
                boolean success = userService.register(fname, lname, uname, gmail, pass, userRole);
                if (success) {

                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "An error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_registerButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        Users u = new Users();
        u.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel background;
    private javax.swing.JTextField firstnameInput;
    private javax.swing.JLabel firstnameLabel;
    private javax.swing.JTextField gmailInput;
    private javax.swing.JLabel gmailLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastnameInput;
    private javax.swing.JTextField passwordInput;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel passwordLabel1;
    private javax.swing.JButton registerButton;
    private javax.swing.JComboBox<String> role;
    private javax.swing.JTextField usernameInput;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
