/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventorysystem;

/**
 *
 * @author 
 */
public class MainMenu extends javax.swing.JFrame {
    private String userRole;

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        UserService userService = UserService.getInstance();
        this.userRole = userService.getUserRole();
        
        if (this.userRole.equals("Admin")) {
            this.userButton.setVisible(true);
        }
        else {
            this.userButton.setVisible(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        inventorySystemLabel = new javax.swing.JLabel();
        incomingOrdersButton = new javax.swing.JButton();
        inventoryButton = new javax.swing.JButton();
        shipmentButton = new javax.swing.JButton();
        supplierButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        clientsButton = new javax.swing.JButton();
        userButton = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inventorySystemLabel.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        inventorySystemLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inventorySystemLabel.setText("INVENTORY SYSTEM");
        jPanel1.add(inventorySystemLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 178, -1));

        incomingOrdersButton.setBackground(new java.awt.Color(75, 130, 245));
        incomingOrdersButton.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        incomingOrdersButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/24/box.png"))); // NOI18N
        incomingOrdersButton.setText("INCOMING ORDERS");
        incomingOrdersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incomingOrdersButtonActionPerformed(evt);
            }
        });
        jPanel1.add(incomingOrdersButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 190, 190, -1));

        inventoryButton.setBackground(new java.awt.Color(75, 130, 245));
        inventoryButton.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        inventoryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/24/track.png"))); // NOI18N
        inventoryButton.setText("INVENTORY");
        inventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryButtonActionPerformed(evt);
            }
        });
        jPanel1.add(inventoryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 230, 190, -1));

        shipmentButton.setBackground(new java.awt.Color(75, 130, 245));
        shipmentButton.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        shipmentButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/24/cargo-truck.png"))); // NOI18N
        shipmentButton.setText("SHIPMENT");
        shipmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shipmentButtonActionPerformed(evt);
            }
        });
        jPanel1.add(shipmentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 270, 190, -1));

        supplierButton.setBackground(new java.awt.Color(75, 130, 245));
        supplierButton.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        supplierButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/24/group.png"))); // NOI18N
        supplierButton.setText("SUPPLIER");
        supplierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierButtonActionPerformed(evt);
            }
        });
        jPanel1.add(supplierButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 310, 190, -1));

        logoutButton.setBackground(new java.awt.Color(75, 130, 245));
        logoutButton.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/24/logout.png"))); // NOI18N
        logoutButton.setText("LOGOUT");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        jPanel1.add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 450, 190, -1));

        clientsButton.setBackground(new java.awt.Color(75, 130, 245));
        clientsButton.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        clientsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/24/store.png"))); // NOI18N
        clientsButton.setText("CLIENT");
        clientsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientsButtonActionPerformed(evt);
            }
        });
        jPanel1.add(clientsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 350, 190, -1));

        userButton.setBackground(new java.awt.Color(75, 130, 245));
        userButton.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        userButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/24/administrator.png"))); // NOI18N
        userButton.setText("USERS");
        userButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userButtonActionPerformed(evt);
            }
        });
        jPanel1.add(userButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 390, 190, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/tablet3.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 10, 550, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryButtonActionPerformed
        Inventory i = new Inventory();
        i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_inventoryButtonActionPerformed

    private void incomingOrdersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incomingOrdersButtonActionPerformed
        IncomingOrders IO = new IncomingOrders();
        IO.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_incomingOrdersButtonActionPerformed

    private void shipmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shipmentButtonActionPerformed
        ShippingOrders SO = new ShippingOrders();
        SO.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_shipmentButtonActionPerformed

    private void supplierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierButtonActionPerformed
        Suppliers S = new Suppliers();
        S.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_supplierButtonActionPerformed

    private void clientsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientsButtonActionPerformed
        Stores S = new Stores();
        S.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_clientsButtonActionPerformed

    private void userButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userButtonActionPerformed
        Users u = new Users();
        u.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_userButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton clientsButton;
    private javax.swing.JButton incomingOrdersButton;
    private javax.swing.JButton inventoryButton;
    private javax.swing.JLabel inventorySystemLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton shipmentButton;
    private javax.swing.JButton supplierButton;
    private javax.swing.JButton userButton;
    // End of variables declaration//GEN-END:variables
}
