/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventorysystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 
 */
public class ShippingOrders extends javax.swing.JFrame {
    /**
     * Creates new form IncomingOrders
     */
    public ShippingOrders() {
        initComponents();
        getShippingOrders();
    }
    
    public static void getShippingOrders() {
        DefaultTableModel tablemodel = (DefaultTableModel)shippingOrdersTable.getModel();
        int tablecount = tablemodel.getRowCount();
        for (int i = tablecount-1; i >= 0; i--) {
            tablemodel.removeRow(i);
        }
        
        String dbName = "InventorySystem";
        String dbUsername = "root";
        String dbPassword = "root";

        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/" + dbName, dbUsername, dbPassword)) {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from shippingorders");
            while (rs.next()) {
                int data1 = rs.getInt("shippingId");
                String data2 = rs.getString("storeNickname");
                String data3 = rs.getString("shippingProductName");
                String data4 = rs.getString("shippingProductDescription");
                double data5 = rs.getDouble("shippingProductPrice");
                int data6 = rs.getInt("shippingProductQuantity");
                double data7 = rs.getDouble("total");
                double data8 = rs.getDouble("markup");
                String data9 = rs.getString("shippingCreated_at");

                String[] shippingOrdersData = {
                    String.valueOf(data1),
                    data2,
                    data3,
                    data4,
                    String.valueOf(data5),
                    String.valueOf(data6),
                    String.valueOf(data7),
                    String.valueOf(data8),
                    data9.split(" ")[0]
                };

                tablemodel.addRow(shippingOrdersData);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "An error occurred: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sectionLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        shippingOrdersTable = new javax.swing.JTable();
        searchLabel = new javax.swing.JLabel();
        productName = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        shipButton = new javax.swing.JButton();
        prepareButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sectionLabel.setFont(new java.awt.Font("Nirmala UI", 1, 28)); // NOI18N
        sectionLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/64/cargo-truck.png"))); // NOI18N
        sectionLabel.setText("  SHIPPING ORDERS");
        jPanel1.add(sectionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 27, -1, -1));

        shippingOrdersTable.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        shippingOrdersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "STORE", "PRODUCT", "DESCRIPTION", "PRICE", "QUANTITY", "TOTAL", "MARKUP", "DATE CREATED"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(shippingOrdersTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 158, 1120, -1));

        searchLabel.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        searchLabel.setForeground(new java.awt.Color(255, 255, 255));
        searchLabel.setText("PRODUCT: ");
        jPanel1.add(searchLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 114, -1, -1));

        productName.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jPanel1.add(productName, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 111, 185, -1));

        searchButton.setBackground(new java.awt.Color(75, 130, 245));
        searchButton.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/24/magnifying-glass.png"))); // NOI18N
        searchButton.setText("SEARCH");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        jPanel1.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 109, 120, -1));

        editButton.setBackground(new java.awt.Color(75, 130, 245));
        editButton.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/24/editing.png"))); // NOI18N
        editButton.setText("EDIT");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        jPanel1.add(editButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 610, 110, -1));

        shipButton.setBackground(new java.awt.Color(75, 130, 245));
        shipButton.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        shipButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/24/cargo-truck.png"))); // NOI18N
        shipButton.setText("DELIVER");
        shipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shipButtonActionPerformed(evt);
            }
        });
        jPanel1.add(shipButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 610, 140, -1));

        prepareButton.setBackground(new java.awt.Color(75, 130, 245));
        prepareButton.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        prepareButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/24/add (1).png"))); // NOI18N
        prepareButton.setText("PREPARE FOR SHIPMENT");
        prepareButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prepareButtonActionPerformed(evt);
            }
        });
        jPanel1.add(prepareButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, -1, -1));

        backButton.setBackground(new java.awt.Color(75, 130, 245));
        backButton.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/24/left-arrow.png"))); // NOI18N
        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 50, 130, -1));

        resetButton.setBackground(new java.awt.Color(75, 130, 245));
        resetButton.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        resetButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/24/undo-arrow.png"))); // NOI18N
        resetButton.setText("RESET");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        jPanel1.add(resetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 110, 120, -1));

        deleteButton.setBackground(new java.awt.Color(75, 130, 245));
        deleteButton.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/24/delete.png"))); // NOI18N
        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        jPanel1.add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 610, 110, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/crates.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 660));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 658));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void prepareButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prepareButtonActionPerformed
        PrepareOrder PO = new PrepareOrder();
        PO.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_prepareButtonActionPerformed

    private void shipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shipButtonActionPerformed
        DefaultTableModel tablemodel = (DefaultTableModel)shippingOrdersTable.getModel();
        int[] sel = shippingOrdersTable.getSelectedRows();
        UserService userService = UserService.getInstance();
        String username = userService.getUsername();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String date = dateFormat.format(new Date());
        try {
            int a=JOptionPane.showConfirmDialog(this,"Are you sure you want to deliver this item/s?");
            
            if (a==JOptionPane.YES_OPTION) {
                String dbName = "InventorySystem";
                String dbUsername = "root";
                String dbPassword = "root";

                try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/" + dbName, dbUsername, dbPassword)) {
                    for (int i = 0; i < sel.length; i++) {
                        String shipProduct = (String) tablemodel.getValueAt(sel[i], 0);
                        String sql = "select * from shippingOrders where shippingId = ?";
                        PreparedStatement ps = con.prepareStatement(sql);

                        ps.setString(1, shipProduct);
                        ps.execute();
                         
                        ResultSet rs = ps.executeQuery();
                         
                        int data1 = 0;
                        String data2 = "";
                        String data3 = "";
                        String data4 = "";
                        double data5 = 0.0;
                        int data6 = 0;
                        double data7 = 0.0;
                        double data8 = 0.0;
                        String data9 = "";

                        while (rs.next()) {
                            data1 = rs.getInt("shippingId");
                            data2 = rs.getString("storeNickname");
                            data3 = rs.getString("shippingProductName");
                            data4 = rs.getString("shippingProductDescription");
                            data5 = rs.getDouble("shippingProductPrice");
                            data6 = rs.getInt("shippingProductQuantity");
                            data7 = rs.getDouble("total");
                            data8 = rs.getDouble("markup");
                            data9 = rs.getString("shippingCreated_at");
                        }
                        
                        double newPrice = data5 + data8;
                        
                        String sql2 = "select * from storeproduct where storeProductName = ?";
                        PreparedStatement ps2 = con.prepareStatement(sql2);
                        
                        ps2.setString(1, data3);
                        ps2.execute();
                         
                        ResultSet rs2 = ps2.executeQuery();
                        if(rs2.next()) {
                            int productQ = rs2.getInt("storeProductQuantity");
                            int newQuantity = productQ + data6;
                            
                            String sql3 = "update storeproduct set storeProductQuantity = ?, total = ?, storeProdcutPrice = ? where storeProductName = ?";
                            PreparedStatement ps3 = con.prepareStatement(sql3);

                            double newTotal = newQuantity * newPrice;
                            ps3.setInt(1, newQuantity);
                            ps3.setDouble(2, newTotal);
                            ps3.setDouble(3, newPrice);
                            ps3.setString(4, data3);
                            ps3.execute();
                        }
                        else {
                            String sql4 = "insert into storeproduct(storeProductName, storeProductDescription, storeProductQuantity, storeProdcutPrice, total, username, storeProductCreated_at, storeNickname) values(?, ?, ?, ?, ?, ?, ?, ?)";
                            PreparedStatement ps4 = con.prepareStatement(sql4);

                            ps4.setString(1, data3);
                            ps4.setString(2, data4);
                            ps4.setInt(3, data6);
                            ps4.setDouble(4, newPrice);
                            ps4.setDouble(5, data7);
                            ps4.setString(6, username);
                            ps4.setString(7, date);
                            ps4.setString(8, data2);
                            ps4.execute();
                        }
                        
                        String sql5 = "Delete from shippingOrders where shippingId = ?";
                        PreparedStatement ps5 = con.prepareStatement(sql5);

                        ps5.setString(1, shipProduct);
                        ps5.execute();
                    }
                    getShippingOrders();
                    JOptionPane.showMessageDialog(null, "Product Shipped.", "Success", JOptionPane.INFORMATION_MESSAGE);
                }
                catch (SQLException ex) {
                    Logger.getLogger(ShippingOrders.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please fill out all required fields.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_shipButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        DefaultTableModel tablemodel = (DefaultTableModel)shippingOrdersTable.getModel();
        int[] sel = shippingOrdersTable.getSelectedRows();
        
        if (sel.length == 0) {
            JOptionPane.showMessageDialog(this, "Please select a data.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        else if (sel.length != 1) {
            JOptionPane.showMessageDialog(this, "Please select only one data.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else {
            int productId = Integer.parseInt((String) tablemodel.getValueAt(sel[0], 0)); 
            
            EditShippingOrder.shippingProductId = productId;
            EditShippingOrder ESO = new EditShippingOrder();
            
            ESO.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        MainMenu MM = new MainMenu();
        MM.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        productName.setText("");
        getShippingOrders();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        String product = productName.getText();
        
        if (product.equals("")) {
            JOptionPane.showMessageDialog(this, "Please input a product.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else {
            DefaultTableModel tablemodel = (DefaultTableModel)shippingOrdersTable.getModel();
            int tablecount = tablemodel.getRowCount();
            for (int i = tablecount-1; i >= 0; i--) {
                tablemodel.removeRow(i);
            }

            String dbName = "InventorySystem";
            String dbUsername = "root";
            String dbPassword = "root";

            try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/" + dbName, dbUsername, dbPassword)) {
                PreparedStatement ps = con.prepareStatement("select * from incomingorders WHERE receivingId = ? or receivingProductName = ? or receivingProductQuantity = ? or receivingProductPrice = ? or supplierNickname = ?");
                ps.setString(1, product);
                ps.setString(2, product);
                ps.setString(3, product);
                ps.setString(4, product);
                ps.setString(5, product);
                ResultSet rs = ps.executeQuery();

                while (rs.next()) {
                    int data1 = rs.getInt("receivingId");
                    String data2 = rs.getString("supplierNickname");
                    String data3 = rs.getString("receivingProductName");
                    String data4 = rs.getString("receivingProductDescription");
                    double data5 = rs.getDouble("receivingProductPrice");
                    int data6 = rs.getInt("receivingProductQuantity");
                    double data7 = rs.getDouble("total");
                    String data8 = rs.getString("IncomingOrderCreated_at");

                    String[] incomingOrdersData = {
                        String.valueOf(data1),
                        data2,
                        data3,
                        data4,
                        String.valueOf(data5),
                        String.valueOf(data6),
                        String.valueOf(data7),
                        data8.split(" ")[0]
                    };

                    tablemodel.addRow(incomingOrdersData);
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "An error occurred: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        DefaultTableModel tablemodel = (DefaultTableModel)shippingOrdersTable.getModel();
        int[] sel = shippingOrdersTable.getSelectedRows();
        UserService userService = UserService.getInstance();
        String username = userService.getUsername();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String date = dateFormat.format(new Date());
        try {
            int a=JOptionPane.showConfirmDialog(this,"Are you sure you want to delete this item/s?");
            
            if (a==JOptionPane.YES_OPTION) {
                String dbName = "InventorySystem";
                String dbUsername = "root";
                String dbPassword = "root";

                try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/" + dbName, dbUsername, dbPassword)) {
                    for (int i = 0; i < sel.length; i++) {
                        String shippingProductId = (String) tablemodel.getValueAt(sel[i], 0);
                        String shippingProduct = (String) tablemodel.getValueAt(sel[i], 2);
                        
                        String sql = "select * from shippingorders where shippingId = ?";
                        PreparedStatement ps = con.prepareStatement(sql);
                        ps.setString(1, shippingProductId);
                        ResultSet rs = ps.executeQuery();
                        
                        int productQuantity = 0;
                        
                        while(rs.next()) {
                            productQuantity = rs.getInt("shippingProductQuantity");
                        }
                        
                        String sql2 = "select * from inventory where inventoryProductName = ?";
                        PreparedStatement ps2 = con.prepareStatement(sql2);
                        ps2.setString(1, shippingProduct);
                        ResultSet rs2 = ps2.executeQuery();
                        
                        while(rs2.next()) {
                            productQuantity = productQuantity + rs2.getInt("inventoryProductQuantity");
                        }
                        
                        String sql3 = "update inventory set inventoryProductQuantity = ? where inventoryProductName = ?";
                        PreparedStatement ps3 = con.prepareStatement(sql3);
                        ps3.setInt(1, productQuantity);
                        ps3.setString(2, shippingProduct);
                        ps3.executeUpdate();
     
                        String sql4 = "Delete from shippingorders where shippingId = ?";
                        PreparedStatement ps4 = con.prepareStatement(sql4);

                        ps4.setString(1, shippingProductId);
                        ps4.execute();
                    }
                    getShippingOrders();
                    JOptionPane.showMessageDialog(null, "Product deletion successful.", "Success", JOptionPane.INFORMATION_MESSAGE);
                }
                catch (SQLException ex) {
                    Logger.getLogger(ShippingOrders.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please fill out all required fields.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShippingOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShippingOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShippingOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShippingOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShippingOrders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel background;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton prepareButton;
    private javax.swing.JTextField productName;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JLabel sectionLabel;
    private javax.swing.JButton shipButton;
    private static javax.swing.JTable shippingOrdersTable;
    // End of variables declaration//GEN-END:variables
}
